### ISSUE TITLE
Not possible to reload the orinal icon

### ISSUE THREAD

**Issue by decembre** [dhanak/identfavicon#2]
I use your addon on firefox 37.0.2.
I use it since a long time, without problem.
But sudently some pined Tab lost their orinal icons to present a auto generated .
I ca't find a way to revert to the orignal.
I try 
- your option panel 
- Find where, in my Firefox profile,  the addon store its infos
  But without luck.

So, How to revert back to the original icon ?
Can you add an option for that ?

Thanks!

**Comment by dhanak** [comment]
Hello,

I have long stopped working on indentfavicon. However, what you ask should
already be doable. Whenever you open a web page, there should be a "Reload
page favicon" in the context menu, put there by the extension. Click that
to try to reload the official favicon for the given page. It happens
sometimes that the retrieval of the favicon times out, and that's why
identfavicon generates a custom icon for the page. Using the forced reload
undoes that. If that doesn't work, you can try adding the domain of the
site as an exception on the options screen; and then select reload from the
menu.

Regards,
David

**Comment by decembre** [comment]
" you can try adding the domain of the
site as an exception on the options screen" : 
Thanks, that good with your help!

By curiosity, where are stored its value .

**Comment by dhanak** [comment]
Somewhere in the preferences of FF, I forgot the exact name of the key, but
if you filter for identfavicon, you should be able to find it.
